### ISSUE TITLE
Organização do Repositório

### ISSUE THREAD

**Issue by rafaelrc7** [AgnerSecurity/AgnerSecurity#1]
Acho que distribuir todo o código fonte dentro de um arquivo zip derrota o propósito de um repositório git. Além de impedir de seguir modificações individuais dos arquivos do projeto, também dificulta navegar pelo código online no GitHub.

**Comment by AgnerSecurity** [comment]
Rafael, primeiramente obrigado pelo feedback, irei em breve reorganizar e colocar no manual junto com a versão 3.0

**Comment by rafaelrc7** [comment]
Ok!
